### ISSUE TITLE
iPhone X(iOS 11 & iOS 12) scanning two QR code at same time.

### ISSUE THREAD

**Issue by sagargondaliya** [TheLevelUp/ZXingObjC#439] opened 2018-09-27 03:53 UTC
I am using this library in my project and now with iPhone X, when two QR code side by side than it scans both at same time.

**Comment by neacao** [comment] 2018-09-27 04:10
@sagargondaliya can you provide the qr code image & also the screenshot after scanned ?

**Comment by sagargondaliya** [comment] 2018-09-27 04:50
Sorry @neacao, QR code are private data , So I can not share with you. I can say that i have tested it on different iOS devices and it sometimes happening on iPhone X(iOS 11) and iPhone X(iOS 12).

**Comment by neacao** [comment] 2018-09-27 06:05
@sagargondaliya do you mean the result show twice for each qr code ?

**Comment by benjohnde** [comment] 2018-09-28 07:51
To be a bit more precise: it can happen that the BarcodeScanner detects both barcodes, one after another. So the delegate gets fired multiple times with either barcodes.

If you want to focus on a single barcode, use scanning rect. If you need both, you will need some custom logic to create two independent images (similar approach to setting a scanning rect) and feed a QRCodeReader with both images.

Closing the issue as this is clearly not a bug.

**Closed by benjohnde** 2018-09-28 07:51 UTC
Labels: question
