### ISSUE TITLE
Scanning PDF417 codes is pretty slow

### ISSUE THREAD

**Issue by kalyanpkumar** [TheLevelUp/ZXingObjC#377] opened 2018-04-20 11:00 UTC
We are working on a app to scan PDF417 barcodes like driving licence barcodes.. But we see that though scan of barcodes is working, its taking time to scan and give the result.. the minimum time we experienced to scan is 20 secs and some times its 10secs... 

for few codes which are taking more time, we have to kill the app and try again and then the scan is working..

So, is there anyway that library performance can be improved??

**Comment by benjohnde** [comment] 2018-06-12 12:42
Could be related to #350 and #314.

The problem is twofold. The first regarding the slow scanning in general may be caused by a bad implementation for PDF417. Which was fixed in the original zxing code long time ago, but still is not ported to the current ZXingObjC version. The second may caused by the crappy ZXCapture implementation.

To improve the overall performance, use 720p and implement your own ZXCapture class (which should handle all the AVCapture methods and pipe the bytearray [apply a scanning rect beforehand] async in to the zxing client).

**Closed by benjohnde** 2018-06-12 12:42 UTC
