### ISSUE TITLE
Not able to restrict ZXCapture from scanning single barcode multiple times. If we call stop method then capture layer goes away. Which is not a good UI experience.

### ISSUE THREAD

**Issue by gadregit** [TheLevelUp/ZXingObjC#173] opened 2014-09-18 06:08 UTC
Hi Guys,
Recently i integration ZXingObjC 3.0.3 alongwith cocoapods. And all is working fine for me. But i am not able to find How do I restrict ZXCapture to scan a single barcode multiple times? Sometimes it just scans 4-5 times in fraction of second.
Thanks.

**Comment by cwalcott** [comment] 2015-03-20 14:01
Looks like a duplicate of #163

**Closed by cwalcott** 2015-03-20 14:01 UTC
